resources:
  Dbp\Relay\BasePersonBundle\Entity\Person:
    types: ['https://schema.org/Person']
    shortName: 'BasePerson'
    normalizationContext:
      groups: ['BasePerson:output', 'LocalData:output']
      jsonld_embed_context: true
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\BasePersonBundle\DataProvider\PersonDataProvider
        uriTemplate: '/base/people/{identifier}'
        openapiContext:
          tags: ["BasePerson"]
          parameters:
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\BasePersonBundle\DataProvider\PersonDataProvider
        uriTemplate: '/base/people'
        openapiContext:
          tags: ['BasePerson']
          parameters:
            - name: search
              in: query
              description: "Search filter (whitespace separated list of search terms to perform a partial, case-insensitive text search on person's full name with)"
              required: false
              type: string
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string
            - name: queryLocal
              in: query
              description: 'Local query parameters to apply'
              type: string

    properties:
      identifier:
        identifier: true
      givenName:
        iri: 'https://schema.org/givenName'
      familyName:
        iri: 'https://schema.org/familyName'
      localData:
        iri: 'https://schema.org/additionalProperty'
