services:
  Dbp\Relay\BasePersonBundle\Service\DummyPersonProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonBundle\API\PersonProviderInterface:
    '@Dbp\Relay\BasePersonBundle\Service\DummyPersonProvider'

  Dbp\Relay\BasePersonBundle\DataProvider\PersonDataProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  # This alias exists, so we can replace the service during tests
  test.PersonProviderInterface:
    alias: 'Dbp\Relay\BasePersonBundle\API\PersonProviderInterface'
    public: true
