services:
  Dbp\Relay\BasePersonBundle\Service\DummyPersonProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonBundle\API\PersonProviderInterface:
    '@Dbp\Relay\BasePersonBundle\Service\DummyPersonProvider'

  Dbp\Relay\BasePersonBundle\DataProvider\PersonDataProvider:
    autowire: true
    autoconfigure: true
